### ISSUE TITLE
How is the mat data in the data folder generated?

### ISSUE THREAD

**Issue by qianqifeng** [SafeRoboticsLab/SHARP#1]
How is the mat data in the data folder generated? Can you provide relevant programs? For example, QMDP_ precomp.mat, HJ_ precomp.mat

**Comment by HaiminClack** [comment]
Uploaded [here](https://github.com/SafeRoboticsLab/SHARP/blob/main/MATLAB/precomp/SHARP_precomp.m).

**Comment by qianqifeng** [comment]
Dear HaiminClack, Thank you very much for your reply. I try to run this program on  personal PC and there was an unknown error when call the function HJIPDE_solve().  In addition,  it can be seen from the results in the paper that only the offline table lookup method (QMDP ) can achieve good control performance. I am very interested in how to use the value function table generated by the dynamic programming algorithm. When I try to reproduce the table by programming, I do not know the generation logic of Markov chain, so can you share the program for calculating the QMDP table? Thank you very much for your help.
