### ISSUE TITLE
Query about QMDP data preprocessing method

### ISSUE THREAD

**Issue by qianqifeng** [SafeRoboticsLab/SHARP#2]
Dear HaiminClack, Thank you very much for your reply. I'm sorry to ask for your help again. I'm a graduate student in mechanical engineering at Jilin University of China, and I'm not good at some numerical calculation methods, such as POMDP.I try to run precomp program on personal PC to get HJ_precomp.mat and there was an unknown error when call the function HJIPDE_solve(). In addition, it can be seen from the results in the paper that only the offline table lookup method (QMDP ) can achieve good control performance. I am very interested in how to use the value function table generated by the dynamic programming algorithm. When I try to reproduce the table by programming, I do not know the generation logic of Markov chain, so can you share the program for calculating the QMDP table? Thank you very much for your help.

**Comment by HaiminClack** [comment]
Hello, please properly install the helperOC toolbox, as indicated in the Dependencies Section of the README file. You can also find a good tutorial there to get familiar with HJ Reachability and grid-based computation. To clarify: SHARP-SMPC and SHARP-QMDP are two different policies and our simulation results clearly show that the former outperforms the latter (statistically). I am afraid that your argument "it can be seen from the results in the paper that only the offline table lookup method (QMDP) can achieve good control performance" is not correct in general. Please read our paper more carefully. Finally, please follow the dynamic programming equation provided in the QMDP section of our paper for computing the SHARP-QMDP policy.
